apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  replicas: 3   # <-- equivalent to --scale app=3
  selector:
    matchLabels:
      app: prisma-app
  template:
    metadata:
      labels:
        app: prisma-app
    spec:
      containers:
        - name: app
          image: 2121g/prisma-app:latest
          ports:
            - containerPort: 3000
          env:
            - name: NODE_ENV
              value: production
            - name: DATABASE_URL
              value: postgresql://postgrestester:PostGreSqlPass82379426@db:5432/my_db?schema=public
